# Generated by Django 3.0.7 on 2020-06-08 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='Post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.PostModel', verbose_name='Пост, к которому прикрепить'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='Title',
            field=models.CharField(default='Заголвок', max_length=100, verbose_name='Заголовок статьи'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='File',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.PostModel', verbose_name='Пост, к которому прикрепить')),
            ],
        ),
    ]
